[build]
  publish = "build"
  command = "bun install && bun run build"

[build.environment]
  VITE_API_URL = "https://homevend-backend.onrender.com/api"

[dev]
  command = "bun run dev"
  port = 8080
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
